# -*- coding: utf-8 -*-
"""visual4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o3bB1Krg-miChPfE5BBWVQkMaJ7Y2YEy
"""

import json
import matplotlib.pyplot as plt
import pandas as pd
import plotly.express as px

data = pd.read_json('applications.anonymized.json')

# form dataframe
plt.scatter(data['tShirtSize'],data['levelOfStudy'],c = data['age'], cmap='coolwarm')
cbar = plt.colorbar()
cbar.set_label('Color based on Age')